apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-scaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70