name: Django-Docker-CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:  
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
              
    - name: Pull image from Docker Hub  
      run: |
        docker pull aubreyz/d10-fe5:latest

    - name: Login to ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Retag image for ECR  
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: frontend
        IMAGE_TAG: ${{ github.sha }} 
      run: |   
        docker tag aubreyz/d10-fe5:latest ${ECR_REGISTRY}/$ECR_REPOSITORY:$IMAGE_TAG
    
    - name: Push image to ECR
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure Kubernetes credentials
      uses: kodermax/kubectl-aws-eks@main
      with: 
        cluster-name: finalv1
        role-arn: ${{ secrets.EKS_ROLE_ARN }}
      env: 
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Deploy to EKS
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: frontend
        IMAGE_TAG: ${{ github.sha }}  
      run: | 
        kubectl set image deployment/$ECR_REPOSITORY container=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1

    # - name: Login to ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1

    # - name: Deploy from ECR 
    #   env:
    #     ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
    #     IMAGE_TAG: latest
    #   uses: kodermax/kubectl-aws-eks@main  
    #   with:
    #     args: |
    #       set image deployment/frontend container=$ECR_REGISTRY/myrepo:$IMAGE_TAG
    #       container=$ECR_REGISTRY/myrepo:$IMAGE_TAG


    # - name: Configure Kubernetes credentials
    #   uses: kodermax/kubectl-aws-eks@main
    #   with:
    #     cluster-name: finalv1
    #     role-arn: ${{ secrets.EKS_ROLE_ARN }}

    # - name: Verify deployment
    #   uses: kodermax/kubectl-aws-eks@main
    #   with:
    #     args: rollout status deployment/frontend

