name: 'AWS Terraform'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  TF_CLOUD_ORGANIZATION: "C4_Final_Proj"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "c4-final-proj"
  CONFIG_DIRECTORY: "./"

jobs:

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    # Use the Bash shell regardless of whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
   
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    - name: Configure TF Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.TF_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TF_SECRET_ACCESS_KEY }}

    - name: Copy state file to S3
      run: | 
        aws s3 cp .terraform/terraform.tfstate s3://c4-kura-final-proj/terraform.tfstate
    
    - name: Get state file from S3
      run: |
        aws s3 cp s3://c4-kura-final-proj/terraform/terraform.tfstate ./terraform.tfstate
   
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
  
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color
    
    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      run: terraform apply -input=false -auto-approve